query rxListReplication(
  $lastId: String!
  $minUpdatedAt: String!
  $limit: Float!
) {
  rxListReplication(
    lastId: $lastId
    minUpdatedAt: $minUpdatedAt
    limit: $limit
  ) {
    id
    updatedAt
    deleted
    title
    description
    calendarDate
    hashedKey
    processing
    categories
    entries {
      id
      hashedKey
      updatedAt
      createdAt
      deleted
      title
      description
      url
      type
      preview {
        ogSiteName
        ogTitle
        ogDescription
        ogImageUrl
        ogAudioUrl
        ogVideoUrl
        embeddedUrl
        color
        type
      }
      calendarDate
      categories
      processing
    }
  }
}
