schema: 'http://api.projectm.localhost/graphql'
documents: ./src/graphql/**/*.gql
generates:
  ./src/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-vue-apollo
    config:
      withCompositionFunctions: true
