version: "3"

services:
  reverse-proxy:
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    ports:
        - '80:80'
        - '8080:8080'
    volumes:
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock
  api:
    container_name: 'projectm-api'
    image: node:14
    ports:
      - '1337:1337'
    volumes:
        - .:/srv/api:rw
    command: yarn api:docker
    working_dir: /srv/api
    env_file:
      - ./.env
    depends_on:
      - mongo
    labels:
        - 'traefik.http.routers.backend.rule=Host(`api.projectm.localhost`)'

  client:
    container_name: 'projectm-client'
    image: node:14
    environment:
       - NUXT_HOST=0.0.0.0
       - NUXT_PORT=3001
    ports:
      - '3001:3001'

    volumes:
        - .:/srv/client:rw
    working_dir: /srv/client
    command: yarn web:dev
    env_file:
      - ./.env
    depends_on:
      - api
    labels:
        - 'traefik.http.routers.frontend.rule=Host(`projectm.localhost`)'



  mongo:
    container_name: 'projectm-mongo'
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db



volumes:
  mongo-data:
    driver: local
