query rxEntryReplication(
  $lastId: String!
  $minUpdatedAt: String!
  $limit: Float!
) {
  rxEntryReplication(
    lastId: $lastId
    minUpdatedAt: $minUpdatedAt
    limit: $limit
  ) {
    id
    title
    description
    url
    type
    preview {
      ogSiteName
      ogTitle
      ogDescription
      ogImageUrl
      embeddedUrl
      type
    }
    categories
    calendarDate
    processing
    updatedAt
    hashedKey
    deleted
    createdAt
    pinned
    archieved
  }
}
